apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: helloworld
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
