# kubectl create deployment balanced --image=kicbase/echo-server:1.0 --dry-run=client --output=yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: balanced
  name: balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balanced
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: balanced
    spec:
      containers:
      - image: kicbase/echo-server:1.0
        name: echo-server
        resources: {}
status: {}
